### PR TITLE
[experimental] Bunch of experimental startup performance boosts

### PR DESCRIPTION
**Pull request by jfckm**

### CODE REVIEW

**Comment by KamilLepek** [comment]
retest this please

**Comment by KamilLepek** [comment]
retest this please

**Comment by KamilLepek** [comment]
retest this please

**Comment by ArkadiuszNeumann** [comment]
retest this please

**Comment by ArkadiuszNeumann** [comment]
retest this please

**Comment by ArkadiuszNeumann** [comment]
retest this please

**Comment by ArkadiuszNeumann** [comment]
retest this please

**Comment by ArkadiuszNeumann** [comment]
retest this please

**Comment by ArkadiuszNeumann** [comment]
retest this please

**Review by mmichal10 — APPROVED** [review]

**Comment by ArkadiuszNeumann** [comment]
retest this please

**Review by rafalste — APPROVED** [review]

**Pull request merged**
