### PR TITLE
Added function for collecting io class stats.

### PR DESCRIPTION
**Pull request by mmichal10**
Stats are parsed and sent ready to introduce them to user.

Signed-off-by: Michal Mielewczyk <michal.mielewczyk@intel.com>

---
This change is [Reviewable](https://reviewable.io/reviews/open-cas/ocf/52)

### CODE REVIEW

**Comment by KamilLepek** [comment]
run unit tests

**Comment by KamilLepek** [comment]
run unit tests

**Comment by KamilLepek** [comment]
run unit tests

**Comment by KamilLepek** [comment]
run unit tests

**Comment by KamilLepek** [comment]
run unit tests

**Comment by KamilLepek** [comment]
run unit tests

**Comment by KamilLepek** [comment]
run unit tests

**Comment by KamilLepek** [comment]
run unit tests

**Comment by KamilLepek** [comment]
run unit tests

**Comment by KamilLepek** [comment]
run unit tests

**Comment by KamilLepek** [comment]
run unit tests

**Comment by KamilLepek** [comment]
run unit tests

**Comment by KamilLepek** [comment]
run unit tests

**Comment by KamilLepek** [comment]
run unit tests

**Comment by KamilLepek** [comment]
run unit tests

**Comment by KamilLepek** [comment]
run unit tests

**Comment by KamilLepek** [comment]
run unit tests

**Comment by KamilLepek** [comment]
run unit tests

**Comment by KamilLepek** [comment]
build

**Comment by michalwy** [comment]
retest this please

**Pull request closed without merging**
