### PR TITLE
[experimental] metadata journalling

### PR DESCRIPTION
**Pull request by arutk**

### CODE REVIEW

**Comment by ArkadiuszNeumann** [comment]
retest this please

**Comment by ArkadiuszNeumann** [comment]
retest this please

**Comment by KamilLepek** [comment]
retest this please

**Comment by KamilLepek** [comment]
retest this please

**Comment by ArkadiuszNeumann** [comment]
retest this please

**Comment by ArkadiuszNeumann** [comment]
retest this please

**Comment by ArkadiuszNeumann** [comment]
retest this please

**Comment by ArkadiuszNeumann** [comment]
retest this please

**Comment by ArkadiuszNeumann** [comment]
retest this please

**Comment by ArkadiuszNeumann** [comment]
retest this please

**Comment by ArkadiuszNeumann** [comment]
retest this please

**Comment by ArkadiuszNeumann** [comment]
retest this please

**Comment by ArkadiuszNeumann** [comment]
retest this please

**Comment by ArkadiuszNeumann** [comment]
retest this please

**Comment by ArkadiuszNeumann** [comment]
retest this please

**Comment by ArkadiuszNeumann** [comment]
retest this please

**Comment by ArkadiuszNeumann** [comment]
retest this please

**Pull request closed without merging**
