### PR TITLE
pyocf: failover functional and power failure recovery tests

### PR DESCRIPTION
**Pull request by arutk**

### CODE REVIEW

**Comment by bkarpins** [comment]
retest this please

**Review by jfckm — APPROVED** [review]

**Comment by bkarpins** [comment]
retest this please

**Review by jfckm — APPROVED** [review]

**Comment by bkarpins** [comment]
retest this please

**Comment by bkarpins** [comment]
retest this please

**Comment by bkarpins** [comment]
retest this please

**Comment by arutk** [comment]
retest this please

**Comment by arutk** [comment]
retest this please

**Review by kmajzero — DISMISSED** [review]

**Review by jfckm — APPROVED** [review]

**Review by kmajzero — APPROVED** [review]

**Pull request merged**
